#!/bin/bash
sed '/<!DOCTYPE/, /Adopt<\/td>/d' |
sed '/<\/table>/, /<\/html>/d' |
sed '/<\/tr>/,/<\/td>/d' |
sed 's/<[^>]*>//g' |
sed "s/\`/\'/g" |
tr [:upper:] [:lower:] |
sed 's/[ ,]/\n/g'  |
sed '/^\s*$/d'   |
tr -d [:blank:] |
tr -c "pk\'mnwlhaeiou" '[\n*]' |
tr -s '\n' |
sort -u
