#!/bin/bash

FILES="$(find ${@} -type f)"  #Use Directory given

for files in $FILES
do
    if grep -s -q -Pa '\x00' "$files"
    then
        continue
    fi
    if LC_ALL=en_US.utf8 grep -q '[^[:print:][:space:]]' "$files"
    then
        continue
    fi
    TEST=$(file $files | cut -d\  -f2)
    if [ $TEST == "UTF-8" ]
    then
        echo "$files" is a UTF-8 file.
    else
	continue
    fi
done
