#!/bin/bash

FILES="$(find ${@} -type f)"  #Use Directory given

for files in $FILES
do
    if grep -s -q -Pa '\x00' "$files"
    then
        continue
    fi
    if LC_ALL=en_US.utf8 grep -q '[^[:print:][:space:]]' "$files"
    then
        continue
    fi
    TEST=$(file $files | cut -d\  -f2)
    if [ $TEST == "UTF-8" ]
    then
	HEAD="$(head -n 1 "$files" | grep -v -e "-\*- coding: utf-8 -\*-")"
	if [ "$HEAD" ]
	then
            echo "$files" is missing a UTF-8 header.
	fi
    else
        continue
    fi
done
